language: node_js
node_js: "12"
services: 
  - postgresql
before_script: psql -c 'create database travis_ci_test;' -U postgres
install:
  - npm install
env: 
  TEST_DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test